export const taskActionsTypes = {
  ADD_NEW_TASK: "ADD_NEW_TASK",
  REMOVE_TASK: "REMOVE_TASK",
  MARK_AS_COMPLETED: "MARK_AS_COMPLETED",

  UPDATE_TASK_START: "UPDATE_TASK_START",
  UPDATE_TASK_SUCCESS: "UPDATE_TASK_SUCCESS",
  UPDATE_TASK_FAILURE: "UPDATE_TASK_FAILURE",

  UPDATE_STATUS_START: "UPDATE_STATUS_START",
  UPDATE_STATUS_SUCCESS: "UPDATE_STATUS_SUCCESS",
  UPDATE_STATUS_FAILURE: "UPDATE_STATUS_FAILURE",

  SET_TASKS_START: "SET_TASKS_START",
  SET_TASKS_SUCCESS: "SET_TASKS_SUCCESS",
  SET_TASKS_FAILURE: "SET_TASKS_FAILURE",
};
