export const userActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SIGNIN_START: "SIGNIN_START",
  SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
  SIGNIN_FAIL: "SIGNIN_FAIL",

  SIGN_OUT_START: "SIGN_OUT_START",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAIL: "SIGN_OUT_FAIL",
};
